using System.IO;

namespace PayPal.PartnerGateway.Cli;

/// <summary>
/// Generates a starter usage file for the detected project style. Every template is standalone -
/// an extension method or a static helper class, never a second entry point - so dropping it into
/// an existing project can never collide with the user's own Program.cs/Main.
/// </summary>
public static class CodeScaffolder
{
    /// <summary>
    /// The path <see cref="Scaffold"/> would write to for <paramref name="project"/>'s kind, without
    /// writing anything. Null for kinds with no scaffold (Worker Service, file-based apps, Unknown).
    /// Use this to check whether a starter file already exists before deciding to overwrite it.
    /// </summary>
    public static string? GetTargetPath(string directory, DetectedProject project)
    {
        if (project.IsFileBasedApp) return null;

        return project.Kind switch
        {
            ProjectFrameworkKind.AspNetCoreWeb => Path.Combine(directory, "Endpoints", "PayPalPaymentEndpoints.cs"),
            ProjectFrameworkKind.Console or ProjectFrameworkKind.ClassLibrary => Path.Combine(directory, "PayPalDemo.cs"),
            _ => null,
        };
    }

    /// <summary>Writes (or overwrites) the starter file for <paramref name="project"/>'s kind, if one applies, and returns its path.</summary>
    public static string? Scaffold(string directory, DetectedProject project)
    {
        var path = GetTargetPath(directory, project);
        if (path == null) return null;

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        var code = project.Kind switch
        {
            ProjectFrameworkKind.AspNetCoreWeb => AspNetCoreEndpointsTemplate,
            _ => StandaloneDemoTemplate,
        };

        File.WriteAllText(path, code);
        return path;
    }

    private const string AspNetCoreEndpointsTemplate = """
        using System.Collections.Generic;
        using PayPal.PartnerGateway;
        using PayPal.PartnerGateway.AspNetCore;
        using PayPal.PartnerGateway.Models;
        using Microsoft.AspNetCore.Builder;
        using Microsoft.AspNetCore.Http;
        using Microsoft.AspNetCore.Routing;

        namespace YourApp.Endpoints;

        /// <summary>
        /// Starter PayPal Checkout Orders + webhook endpoints. Call app.MapPayPalPaymentEndpoints()
        /// from Program.cs after builder.Services.AddPayPalPartnerGateway(builder.Configuration).
        /// Generated by 'paypal-partner init' - edit freely, or delete if you'd rather wire this up yourself.
        /// </summary>
        public static class PayPalPaymentEndpoints
        {
            public static IEndpointRouteBuilder MapPayPalPaymentEndpoints(this IEndpointRouteBuilder app)
            {
                // 1. Create an order for the buyer to approve.
                app.MapPost("/payments/orders", async (PayPalPartnerClient client) =>
                {
                    var order = await client.Orders.CreateAsync(new OrderRequest
                    {
                        Intent = "CAPTURE",
                        PurchaseUnits = new List<PurchaseUnit>
                        {
                            new() { Amount = new AmountWithBreakdown(10.00m, "USD"), Description = "Order from YourApp" }
                        }
                    });

                    return order.IsSuccess
                        ? Results.Ok(new { orderId = order.Data!.Id, approvalUrl = order.Data.ApprovalUrl })
                        : Results.BadRequest(new { error = order.Error?.Message, details = order.Error?.Details });
                });

                // 2. Capture payment once the buyer has approved the order.
                app.MapPost("/payments/orders/{orderId}/capture", async (string orderId, PayPalPartnerClient client) =>
                {
                    var capture = await client.Orders.CaptureAsync(orderId);
                    return capture.IsSuccess ? Results.Ok(capture.Data) : Results.BadRequest(capture.Error);
                });

                // 3. Receive and verify PayPal webhook notifications.
                app.MapPayPalPartnerWebhook("/payments/webhooks/paypal",
                    onSuccess: async (result, ctx) =>
                    {
                        // TODO: update your database - result.Event.EventType / result.Event.Resource
                    },
                    onFailure: async (result, ctx) =>
                    {
                        // TODO: log the failed verification for investigation
                    });

                return app;
            }
        }

        """;

    private const string StandaloneDemoTemplate = """
        using System;
        using System.Collections.Generic;
        using System.Threading.Tasks;
        using PayPal.PartnerGateway;
        using PayPal.PartnerGateway.Models;

        namespace YourApp;

        /// <summary>
        /// Sample PayPal.PartnerGateway usage - call PayPalDemo.RunAsync() from wherever you want to try it,
        /// or delete this file. Generated by 'paypal-partner init'.
        /// </summary>
        public static class PayPalDemo
        {
            public static async Task RunAsync()
            {
                // Reads PAYPAL_CLIENT_ID / PAYPAL_CLIENT_SECRET / PAYPAL_ENVIRONMENT env vars,
                // or pass a PayPalPartnerConfig explicitly - see appsettings/env vars this tool configured.
                var client = new PayPalPartnerClient();

                var order = await client.Orders.CreateAsync(new OrderRequest
                {
                    Intent = "CAPTURE",
                    PurchaseUnits = new List<PurchaseUnit>
                    {
                        new() { Amount = new AmountWithBreakdown(10.00m, "USD"), Description = "Order from YourApp" }
                    }
                });

                Console.WriteLine(order.IsSuccess ? $"Approval URL: {order.Data!.ApprovalUrl}" : $"Error: {order.Error!.Message}");
            }
        }

        """;
}
